DFE-Digital/ey-qualifications-prototype

- app/views/current/r1/search-results.html
Changed the text in the search box from 'Level 3 Early Years' to 'NCFE CACHE Level 3 Diploma in Early Years Education and Care'
Removed all of the qualifications from the result list except 'NCFE CACHE Level 3 Diploma in Early Years Education and Care (Early Years Educator)'
Kept ‘The qualification I am looking for is not on this list’
Changed the result list heading from '8 results' to '1 result'
> updating search results - r1

- app/data/qualifications.json
- app/data/session-data-defaults.js
- app/routes.js
- app/views/current/r8/_routes.js
- app/views/current/r8/eyq-223-v1.html
- app/views/current/r8/eyq-223-v2-poc.html
- app/views/current/r8/eyq-223.html
- app/views/current/r8/eyq-224-checked.html
- app/views/current/r8/eyq-224.html
- app/views/current/r8/eyq-300-checked.html
- app/views/current/r8/eyq-300-v1.html
- app/views/current/r8/eyq-300.html
- app/views/current/r8/eyq-301-v1.html
- app/views/current/r8/index.html
- app/views/current/r8/not-listed.html
- app/views/current/r8/not-on-list.html
- app/views/current/r8/q1.html
- app/views/current/r8/q1outsideuk.html
- app/views/current/r8/q1scotwalirl.html
- app/views/current/r8/q2.html
- app/views/current/r8/q3.html
- app/views/current/r8/q3l21419.html
- app/views/current/r8/q4.html
- app/views/current/r8/qualification-detail.html
- app/views/current/r8/search-results.html
- app/views/current/r8/start.html
- app/views/index.html
new user flow for round 4 of UR
> round 4 UR

- app/views/current/r8/search-results.html
> Updated to add in search button on search results page

- app/views/current/r10/_routes.js
> Minor tweak to the logic

- app/views/current/r10/q1-error.html
- app/views/current/r10/q2-error.html
- app/views/current/r10/q2.html
- app/views/current/r10/q3-error.html
- app/views/current/r10/q4-error.html
- app/views/current/r10/search-results.html
- amended error messages
- added more hint text to the date page
- removed "matching" from "X matching qualifications"
> Error message amends

- app/data/qualifications.json
- app/views/current/r10/search-results.html
- added additionalRequirementsNumber to json
- added conditional code to show the number of requirements, or hide that line if there aren't any
> Additional requirements

- app/views/current/r10/eyq-223-checked.html
- app/views/current/r10/eyq-223.html
- app/views/current/r10/eyq-224-checked.html
- app/views/current/r10/eyq-224-confirm-error.html
- app/views/current/r10/eyq-224-confirm.html
- app/views/current/r10/eyq-224.html
- app/views/current/r10/eyq-300-checked.html
- app/views/current/r10/eyq-300-confirm-error.html
- app/views/current/r10/eyq-300-confirm.html
- app/views/current/r10/eyq-300.html
- app/views/current/r10/q1-error.html
- app/views/current/r10/q1.html
- app/views/current/r10/q1outsideuk.html
- app/views/current/r10/q1scotwalirl.html
- app/views/current/r10/q2-error.html
- app/views/current/r10/q2.html
- app/views/current/r10/q3-error.html
- app/views/current/r10/q3.html
- app/views/current/r10/q4-error.html
- app/views/current/r10/q4.html
- app/views/current/r10/search-results.html
Updated all the generic backlinks in the existing pages to specific ones
> updated backlinks to be specific

- app/data/qualifications.json
- app/views/current/r10/_routes.js
- app/views/current/r10/eyq-300-checked.html
- app/views/current/r10/eyq-300-confirm-error.html
- app/views/current/r10/eyq-300-confirm.html
- app/views/current/r10/eyq-300.html
- app/views/current/r10/q3-error.html
- app/views/current/r10/q3.html
- app/views/current/r10/q4-error.html
- Updated header to 'Confirm qualification'
- Added question above radio options
- Updated No option to 'No, select another qualification' 
- Changed the link destination to 'Select the qualification'
- Updated the error page accordingly
> Changes to the confirmation page layout

- app/views/current/r10/eyq-293.html
Removed please from eyq-293.html
Added the real links to the QAA subject benchmark statement and definition of assessed practice.
> Remaining changes for #5 in our list

- app/views/current/r10/q4-error.html
Updated the error message in 'What is the awarding organisation?' page to shorten it and make it more concise
> Update error message in q4

- app/views/current/r10/eyq-293-checked.html
- app/views/current/r10/eyq-75-checked.html
- Added some space between the last horizontal line and 'Providers must...'
> Add space after the last level

- app/assets/downloads/certificate-level3-ncfe.pdf
- app/assets/downloads/certificate-level3-nfce.pdf
- app/data/qualifications.json
- app/views/current/r10/eyq-301-v1.html
- app/views/current/r10/eyq-75-checked.html
- app/views/current/r10/eyq-75-confirm-error.html
- app/views/current/r10/eyq-75-confirm.html
- app/views/documents.html
- Remove old eyq-75 document 
- Added new eyq-75 document with level 3 in the certificate name
- Updated all the references to that certificate so the correct information gets displayed on the screen
> Update certificate eyq-75

- app/views/current/r10/eyq-293-checked.html
- app/views/current/r10/eyq-75-checked.html
- Added new "requirements for all staff section"
- Removed Unqualified dropdown
- Removed L6 details for EYQ-75 as qual is only level 3
> Added new "Requirements for all staff" section

- app/views/current/r10/eyq-293-checked.html
- app/views/current/r10/eyq-75-checked.html
- Fixed spacing between levels in Your result page.
> Fix spacing between levels

- app/views/current/r10/eyq-293-checked.html
- app/views/current/r10/eyq-293-confirm-error.html
- app/views/current/r10/eyq-293-confirm.html
- app/views/current/r10/eyq-293.html
Updated the qualification level to Degree with honours for eyq-293 because in Confirm qualification, Check the additional requirements, and Your result pages it says Level 6.
> Changed level 6 for degree with honours in eyq-293

- app/views/current/r10/eyq-223-checked.html
- app/views/current/r10/eyq-224-checked.html
- app/views/current/r10/eyq-300-checked.html
- Updated levels, tags and content within details component for eyq 223, 224 and 300 to match the changes made for eyq 75 and 293
> Update levels and tags in eyq 223, 224 and 300

- app/views/current/r11/q2-error.html
- app/views/current/r11/q2.html
- Updated hint text in When was the qualification started to 'For example 3 2014' to follow GDS style guide
> Updated hint text in When was the qualification started

- app/views/current/r11/eyq-223.html
- app/views/current/r11/eyq-224.html
- app/views/current/r11/eyq-293.html
- app/views/current/r11/eyq-300.html
- Removed inset text about bookmarking the page in Check the additional requirements page
- Remove "please' in the questions section in old ey quals
> Remove inset text in Check the additional requirements page

- app/views/current/r11/eyq-223.html
- app/views/current/r11/eyq-224-confirm-error.html
- Updated error message and No radio option copy for eyq 224 because it hadn't been updated with the others did
- Remove a duplicated attribute name
> Correct error in eyq 224 confirm error page

- app/views/current/r11/eyq-293-checked.html
- app/views/current/r11/eyq-293-confirm-error.html
- app/views/current/r11/eyq-293-confirm.html
- app/views/current/r11/eyq-293.html
- app/views/current/r11/eyq-75-checked.html
- app/views/current/r11/eyq-75-confirm-error.html
- app/views/current/r11/eyq-75-confirm.html
- Added eyq-75 and eyq-293, quals tested in UR with r10
> Added eyq-75 and 293

- app/views/current/r11/eyq-293-checked.html
- app/views/current/r11/eyq-293-confirm-error.html
- app/views/current/r11/eyq-293-confirm.html
- app/views/current/r11/eyq-293.html
- app/views/current/r11/eyq-75-checked.html
- app/views/current/r11/eyq-75-confirm-error.html
- app/views/current/r11/eyq-75-confirm.html
- Removed inset text on the Check the additional requirements page 
- Organised the code for qual pages
> Removed inset text in additional requirements page and organise code

- app/views/index.html
Removed code from previous version of index file
> Removed code from previous version of index file

- app/views/current/r11/q2-error.html
- app/views/current/r11/q2.html
- Added content below the header
- Added detail component explaining why we ask for the qualification start date
> Added extra information about start date

- app/views/current/r11/start.html
- Updated the second bullet point to 'the date the qualification was started'
> Update second bullet point in homepage

- app/views/current/r11/q3.html
> Added hint text for level 6

- app/views/current/r11/eyq-240-requirement1-error.html
- app/views/current/r11/eyq-240-requirement1.html
- app/views/current/r11/eyq-240-requirements-check.html
- app/views/current/r11/eyq-293-requirement1-error.html
- app/views/current/r11/eyq-293-requirement1.html
- app/views/current/r11/eyq-293-requirement2-error.html
- app/views/current/r11/eyq-293-requirement2.html
- app/views/current/r11/eyq-293-requirements-check.html
- app/views/current/r11/q1-error.html
- app/views/current/r11/q1.html
- app/views/current/r11/q2-error.html
- app/views/current/r11/q2.html
- app/views/current/r11/q3-error.html
- app/views/current/r11/q3.html
- app/views/current/r11/q4-error.html
- app/views/current/r11/q4.html
- app/views/current/r11/start.html
Updated font sizes so that all headers are now xl and subheaders are l
> Font sizes updated

- app/views/current/r11/eyq-240-checked.html
- app/views/current/r11/eyq-240-requirement1.html
- app/views/current/r11/eyq-240-requirements-check.html
- app/views/current/r11/eyq-293-checked.html
- app/views/current/r11/eyq-293-requirement2-error.html
- app/views/current/r11/eyq-293-requirement2.html
- app/views/current/r11/eyq-293-requirements-check.html
- Updated requirements questions for each qual we're testing in UR round 6
- Updated statements for each qual on the Qualification result page
> Updated requirements questions and statements

- app/views/current/r11/eyq-293-requirement1.html
Updated requirement question 1 in eyq-293
> Update requirement question 1

- app/views/current/r11/eyq-240-checked.html
- app/views/current/r11/eyq-293-checked.html
- Updated the backlink text on the 'Qualification result' page
- Updated the backlink destination on the 'Qualification result' page
> Updated backlink in qualification result page

- app/views/current/r11/search-results.html
Fixed issue when awarding organisation is not on the list
> Fixed issue when awarding organisation is not on the list

- app/views/current/r11/eyq-240-checked.html
- app/views/current/r11/eyq-240-confirm-error.html
- app/views/current/r11/eyq-240-confirm.html
- app/views/current/r11/eyq-240-requirement1-error.html
- app/views/current/r11/eyq-240-requirement1.html
- app/views/current/r11/eyq-240-requirements-check.html
- app/views/current/r11/eyq-293-checked.html
- app/views/current/r11/eyq-293-confirm-error.html
- app/views/current/r11/eyq-293-confirm.html
- app/views/current/r11/eyq-293-requirement1-error.html
- app/views/current/r11/eyq-293-requirement1.html
- app/views/current/r11/eyq-293-requirement2-error.html
- app/views/current/r11/eyq-293-requirement2.html
- app/views/current/r11/eyq-293-requirements-check.html
- app/views/current/r11/not-on-list.html
- app/views/current/r11/q1-error.html
- app/views/current/r11/q1.html
- app/views/current/r11/q2-error.html
- app/views/current/r11/q2.html
- app/views/current/r11/q3-error.html
- app/views/current/r11/q3.html
- app/views/current/r11/q4-error.html
- app/views/current/r11/q4.html
- app/views/current/r11/search-results.html
- app/views/current/r11/start.html
Fixed inconsistencies in headers size
> Fixed inconsistencies in headers size

- app/views/current/r11/eyq-293-confirm-error.html
- app/views/current/r11/eyq-293-confirm.html
Fixed error in qualification level for eyq-293 on the Confirm qualification page
> Fixed error in qualification level for eyq-293

- app/views/current/r11/search-results.html
Changed what's displayed if 'not sure' in the AO question is selected
> Change what's displayed if 'not sure' for AO selected

- app/views/current/r11/eyq-293-requirement2.html
Remove second sentence in details in eyq-293requirement2
> Removed second sentence from details in requirement2

- app/views/current/r11/_routes.js
- app/views/current/r11/eyq-240-checked.html
- app/views/current/r11/eyq-293-checked.html
Updated the Check another qualification button so it calls the reset-filters logic before redirecting to q1
> Updated the Check another qualification button

- app/views/current/r11/eyq-293-confirm-error.html
- app/views/current/r11/eyq-293-confirm.html
Added inset text with information about various awarding organisation on the 'Confirm qualification' page
> Add inset text with info about various

- app/views/current/r11/search-results.html
- Added content for how to improve the search if no matching results that only appears if there are no qualifications found (= 0)
> Added content for how to improve the search if no matching results

- app/views/current/r12/q3-error.html
- app/views/current/r12/q3.html
Updated hint text for level 6 to include QTS, EYTS and EYPS
> Updated hint text for level 6

- app/views/current/r12/qts-checked.html
- app/views/current/r12/qts-confirm-error.html
- app/views/current/r12/qts-confirm.html
- Updated the Confirm qualification page with QTS details
- Updated the Qualification result page with QTS details
- Changed backlink text and destination on the Qualification result page
> Qts journey

- app/views/current/r12/_routes.js
- app/views/current/r12/eyq-240-checked.html
- app/views/current/r12/eyq-240-confirm-error.html
- app/views/current/r12/eyq-240-confirm.html
- app/views/current/r12/eyq-240-requirement1-error.html
- app/views/current/r12/eyq-240-requirement1.html
- app/views/current/r12/eyq-240-requirements-check.html
- app/views/index.html
- Updated index page
- Added page for level 3 qualification
- Added routing
> Accessibility journeys

- app/views/index.html
Removed reference to r12 having to be tested in research
> Removed content

- app/routes.js
- app/views/current/r13/_routes.js
- app/views/current/r13/eyq-500-checked.html
- app/views/current/r13/eyq-500-confirm-error.html
- app/views/current/r13/eyq-500-confirm.html
- app/views/current/r13/eyq-500-requirement1-error.html
- app/views/current/r13/eyq-500-requirement1.html
- app/views/current/r13/eyq-500-requirement2-error.html
- app/views/current/r13/eyq-500-requirement2.html
- app/views/current/r13/eyq-500-requirement3-error.html
- app/views/current/r13/eyq-500-requirement3.html
- app/views/current/r13/eyq-500-requirements-check.html
- app/views/current/r13/q1-error.html
- app/views/current/r13/q1.html
- app/views/current/r13/q2-error.html
- app/views/current/r13/q2.html
- app/views/current/r13/q3-error.html
- app/views/current/r13/q3.html
- app/views/current/r13/q4-error.html
- app/views/current/r13/q4.html
- app/views/current/r13/qts-checked.html
- app/views/current/r13/qts-confirm-error.html
- app/views/current/r13/qts-confirm.html
- app/views/current/r13/search-results.html
- app/views/current/r13/start.html
- Added r13 folder
- Updated routes
> Add r13 folder

- app/views/current/r13/eyq-500-checked.html
- updated heading
- added new 'result for this qualification' section
- updated content under 'staff:child ratios for this qualification'
- updated levels to h3
> Update result page

- app/views/current/r13/eyq-500-checked.html
Updated link to secondary button on the Qualification result page
> Updated link to secondary button

- app/views/current/r13/q2-error.html
- app/views/current/r13/q2.html
- app/views/current/r13/search-results.html
Made all the necessary changes to display specific error messages for both date started and date awarded
> Fix date awarded error

- app/views/current/r13/search-results.html
Changed 'x qualification found' to 'x qualification found based on your answers' for when >1 qualifications found
> Added incomplete heading

- app/views/current/r13/search-results.html
- added grey horizontal under tips for improving your search
- adjusted spacing
> Fixed spacing

- app/views/current/r13/_routes.js
- app/views/current/r13/eyq-500-checked-no-full-and-relevant.html
- app/views/current/r13/eyq-500-requirement1-error.html
- app/views/current/r13/eyq-500-requirement1.html
- app/views/current/r13/eyq-500-requirement2-error.html
- app/views/current/r13/eyq-500-requirement2.html
- app/views/current/r13/eyq-500-requirement3-error.html
- app/views/current/r13/eyq-500-requirement3.html
- app/views/current/r13/eyq-500-requirements-check.html
- app/views/index.html
Built the not full and relevant qualification journey
> No full relevant journey

- app/views/current/r13/_routes.js
- app/views/current/r13/eyq-500-checked-no-full-and-relevant.html
- app/views/current/r13/eyq-500-checked.html
- app/views/current/r13/eyq-500-confirm-error.html
- app/views/current/r13/eyq-500-confirm.html
- app/views/current/r13/search-results.html
- converted all the hardcoded information into dynamic
- changed code so now months inputted in numbers are displayed in text on the 'Qualification check' page
> Dynamic content

- app/views/current/r13/search-results.html
Updated tag from h2 m to h3 m on 'If you cannot find the qualification' section on the 'Select a qualification' page
> Updated tag

- app/routes.js
- app/views/current/r14/_routes.js
- app/views/current/r14/check-answers.html
- app/views/current/r14/check-your-answers.html
- app/views/current/r14/eyq-240-checked-full-and-relevant.html
- app/views/current/r14/eyq-240-checked.html
- app/views/current/r14/eyq-240-confirm-error.html
- app/views/current/r14/eyq-240-confirm.html
- app/views/current/r14/eyq-240-requirement1-error.html
- app/views/current/r14/eyq-240-requirement1.html
- app/views/current/r14/eyq-240-requirements-check.html
- app/views/current/r14/q1-error.html
- app/views/current/r14/q1.html
- app/views/current/r14/q2-error-date-awarded.html
- app/views/current/r14/q2-error-date-started-awarded.html
- app/views/current/r14/q2-error-date-started.html
- app/views/current/r14/q2.html
- app/views/current/r14/q3-error.html
- app/views/current/r14/q3.html
- app/views/current/r14/q4-error.html
- app/views/current/r14/q4.html
- app/views/current/r14/search-results.html
- app/views/current/r14/start.html
- created version r14 folder
- added a new Check your answers page
- updated all the other pages and routes
> Create r14 version

- app/views/current/r14/search-results.html
- Made content changes
- Removed Your answers section from the left-hand side
- Moved information inputted below the heading
> New select qualification page

- app/views/index.html
- updated version r13 and r14 status
> Update version status

- app/views/current/r14/_routes.js
- app/views/current/r14/q4-error.html
- app/views/current/r14/q4.html
- app/views/current/r14/search-results.html
Changed action naming to include post at the end instead of at the beginning
> Fixed action naming

- app/views/index.html
- added new row for r15 version
> Added new version to homepage

- app/routes.js
- app/views/current/r15/_routes.js
- app/views/current/r15/check-your-answers.html
- app/views/current/r15/eyq-240-checked.html
- app/views/current/r15/eyq-240-confirm-error.html
- app/views/current/r15/eyq-240-confirm.html
- app/views/current/r15/eyq-240-requirement1-error.html
- app/views/current/r15/eyq-240-requirement1.html
- app/views/current/r15/eyq-240-requirements-check.html
- app/views/current/r15/q1-error.html
- app/views/current/r15/q1.html
- app/views/current/r15/q2-error-date-awarded.html
- app/views/current/r15/q2-error-date-started-awarded.html
- app/views/current/r15/q2-error-date-started.html
- app/views/current/r15/q2.html
- app/views/current/r15/q3-error.html
- app/views/current/r15/q3.html
- app/views/current/r15/q4-error.html
- app/views/current/r15/q4.html
- app/views/current/r15/search-results.html
- app/views/current/r15/start.html
Updated href and routing for r15
> New version file

- app/views/current/r15/eyq-292-confirm.html
Fixed the issue of various awarding organisations not showing on the 'Confirm qualification' page
> Added dynamic data

- app/views/current/r15/_routes.js
- app/views/current/r15/eyq-236-checked.html
- app/views/current/r15/eyq-236-confirm-error.html
- app/views/current/r15/eyq-236-confirm.html
- app/views/current/r15/eyq-292-confirm-error.html
Added new level 3 journey to test in round 11 and fixed a few issues that would have been an issue for level 6 otherwise
> New level 3 journey added
